I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 46, in <module>
    show python_logo at halfsize, right
NameError: name 'halfsize' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/hedley/script.rpyc", line 46, in script
  File "/home/hedley/Documents/renpy/renpy/ast.py", line 1064, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/home/hedley/Documents/renpy/renpy/ast.py", line 1025, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "/home/hedley/Documents/renpy/renpy/python.py", line 1490, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/hedley/Documents/renpy/renpy/python.py", line 1485, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 46, in <module>
    show python_logo at halfsize, right
NameError: name 'halfsize' is not defined

Linux-3.19.0-32-generic-x86_64-with-debian-jessie-sid
Ren'Py 6.99.8.959
Programar con Python 0.0
