I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: could not find label 'q23'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/hedley/script.rpyc", line 1060, in script
  File "/home/hedley/Documents/renpy/renpy/ast.py", line 1519, in execute
    rv = renpy.game.script.lookup(target)
  File "/home/hedley/Documents/renpy/renpy/script.py", line 843, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'q23'.

Linux-3.19.0-32-generic-x86_64-with-debian-jessie-sid
Ren'Py 6.99.8.959
Programar con Python 0.0
