I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 55, in <module>
    $ now_playing=re.sub(re.compile(r'\.mp3$*'), '', musica)
error: nothing to repeat

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/home/hedley/script.rpyc", line 55, in script
  File "/home/hedley/Documents/renpy/renpy/ast.py", line 806, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/hedley/Documents/renpy/renpy/python.py", line 1577, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 55, in <module>
    $ now_playing=re.sub(re.compile(r'\.mp3$*'), '', musica)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/re.py", line 194, in compile
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/re.py", line 251, in _compile
error: nothing to repeat

Linux-3.19.0-32-generic-x86_64-with-debian-jessie-sid
Ren'Py 6.99.10.1227
Programar con Python 0.0
